# Generated by Django 5.0 on 2024-09-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("basket", models.JSONField(default=dict)),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(blank=True, max_length=64, null=True)),
                ("email", models.EmailField(max_length=64)),
                ("address", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Создан"),
                            (1, "Оплачен"),
                            (2, "В пути"),
                            (3, "Доставлен"),
                        ],
                        default=0,
                    ),
                ),
            ],
        ),
    ]
