# Generated by Django 5.0 on 2024-01-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0002_ordermodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="email",
            field=models.CharField(max_length=64),
        ),
    ]
