# Generated by Django 5.0 on 2024-01-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0004_ordermodel_basket_ordermodel_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="email",
            field=models.EmailField(max_length=64),
        ),
    ]
