# Generated by Django 5.0 on 2024-02-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_app", "0002_categorymodel_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsmodel",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
