# Generated by Django 5.0 on 2024-02-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_app", "0003_productsmodel_stripe_price_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsmodel",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
